Layout/LineLength:
  Exclude:
    - 'test/**/*.rb'

Metrics/MethodLength:
  Max: 20

Style/Documentation:
  Enabled: false

Gemspec/RequiredRubyVersion:
   Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

